version: '2'
services:
  # db:
  #   image: eboraas/apache-php
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - .:/var/www/html/
  web:
    image: frontend
    ports:
      - 8000:8000
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/www/web/
    working_dir: /www/web
    command: sh
    container_name: web
    stdin_open: true
    tty: true
    # entrypoint: /www/docker-start.sh