import "../bower_components/requestAnimationFrame/requestAnimationFrame.js";
import { isNodeList } from "./gn/isNodeList";
import { append } from "./gn/append";
import { createElement } from "./gn/createElement";
import { ready } from "./gn/ready";
import { extend } from "./gn/extend";
import { getClosest } from "./gn/getClosest";
import { getHeight } from "./gn/getHeight";
import { getOffsetLeft } from "./gn/getOffsetLeft";
import { getOffsetTop } from "./gn/getOffsetTop";
import { getOuterHeight } from "./gn/getOuterHeight";
import { getOuterWidth } from "./gn/getOuterWidth";
import { getParents } from "./gn/getParents";
import { getParentsUntil } from "./gn/getParentsUntil";
import { getSiblings } from "./gn/getSiblings";
import { getSupportedProp } from "./gn/getSupportedProp";
import { getWidth } from "./gn/getWidth";
import { indexOf } from "./gn/indexOf";
import { isInViewport } from "./gn/isInViewport";
import { optimizedResize } from "./gn/optimizedResize";
import { prepend } from "./gn/prepend";
import { unwrap } from "./gn/unwrap";
import { wrap } from "./gn/wrap";
import { wrapAll } from "./gn/wrapAll";

export var gn = (function (g) {
  g.isNodeList = isNodeList;
  g.append = append;
  g.createElement = createElement;
  g.ready = ready;
  g.extend = extend;
  g.getClosest = getClosest;
  g.getHeight = getHeight;
  g.getOffsetLeft = getOffsetLeft;
  g.getOffsetTop = getOffsetTop;
  g.getOuterHeight = getOuterHeight;
  g.getOuterWidth = getOuterWidth;
  g.getParents = getParents;
  g.getParentsUntil = getParentsUntil;
  g.getSiblings = getSiblings;
  g.getSupportedProp = getSupportedProp;
  g.getWidth = getWidth;
  g.indexOf = indexOf;
  g.isInViewport = isInViewport;
  g.optimizedResize = optimizedResize;
  g.prepend = prepend;
  g.unwrap = unwrap;
  g.wrap = wrap;
  g.wrapAll = wrapAll;

  return g;
})(window.gn || {});

var myFun = () => 19;
myFun();
